export const changelog = [
    "0.3.16",
    "* TaigaChat is ready for early beta-test!",
    "* A lot of backend changes",
    "* A lot of frontend changes"
]

/*
this is the old changelog:
export const changelog = [
    "0.3.4",
    "* Added push-to-talk",
    "0.3.3",
    "* Improved the editing of existing messages according to user feedback",
    "* Began working on video conferencing",
    "0.3.1",
    "* If client connects to a newer server, an update-check is automatically performed",
    "0.3.0",
    "* Restructured the protocol",
    "0.2.2",
    "* Implemented instance locking",
    "* Fixed bug with the strftime implementation",
    "* Can now change voice input device dynamically from the client",
    "0.2.1",
    "* Can now change message timestamp format",
    "* Improved arrow-up edit",
    "* Error feedback no longer covers bottom screen",
    "* Added more padding between channels and rooms",
    "* Fixed the \\ escape sequence for text messages",
    "0.2.0",
    "* Improved voice channel stability",
    "0.1.39",
    "* Improved WebRTC disconnect and reconnect",
    "0.1.37",
    "* Arrow up will automatically start editing user's latest message",
    "* Can no longer press edit on someone else's message",
    "0.1.35",
    "* Added auto-start to the Windows version",
    "0.1.34",
    "* Changed the layout of settings in mobile mode",
    "* Downloading attachments no longer disconnects users from VC",
    "0.1.30",
    "* Clicking links does not cause a reconnect anymore",
    "* There is now a primitive form of speech indication",
    "0.1.29",
    "* Added a send button",
    "0.1.28",
    "* Spellcheck menu",
    "* Notifications now detect window focus",
    "* Improved the auto-updater",
    "* Added offline-away-online status indication",
    "0.1.27",
    "* The stylesheets have been rewritten to use CSS variables",
    "* Can now copy image file from the image viewer",
    "* MOV files now present as downloadable files instead",
    "0.1.21",
    "* Older clients outside appData automatically restart to the newest version",
    "* Now shows version under Settings/Misc",
    "* Now remembers window position after close",
    "0.1.19",
    "* The updater now shows what version will be downloaded",
    "* Fixed the NaN issue with the auto-updater",
    "0.1.18",
    "* Notifications don't show for rooms you have selected",
    "* Rooms now have indicators for unseen messages",
    "0.1.16",
    "* Proper server-side deafen",
    "* Usernames are now set automatically if user joins via central server",
    "* It is now possible to adjust audio levels per userID",
    "* Playing of audio files (0.1.10)",
    "* Experimental PWA support",
    "0.1.14",
    "* Improved the auto-downloader",
    "0.1.10",
    "* Debugging mode for Android",
    "* Larger mobile top bar size",
    "* Words don't break in ugly ways anymore",
    "* Fixed drag and dropping of files",
    "* Message box now reacts to being focused and unfocused",
    "* Began inviting more users",
    "* Added a changelog",
];*/
